config/routes.rb
# == Route Map
#
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                                 /assets                                                                                           Propshaft::Server
#                       rails_health_check GET    /up(.:format)                                                                                     rails/health#show
#                              new_session GET    /session/new(.:format)                                                                            sessions#new
#                             edit_session GET    /session/edit(.:format)                                                                           sessions#edit
#                                  session GET    /session(.:format)                                                                                sessions#show
#                                          PATCH  /session(.:format)                                                                                sessions#update
#                                          PUT    /session(.:format)                                                                                sessions#update
#                                          DELETE /session(.:format)                                                                                sessions#destroy
#                                          POST   /session(.:format)                                                                                sessions#create
#                                   papers GET    /papers(.:format)                                                                                 papers#index
#                                          POST   /papers(.:format)                                                                                 papers#create
#                                new_paper GET    /papers/new(.:format)                                                                             papers#new
#                               edit_paper GET    /papers/:id/edit(.:format)                                                                        papers#edit
#                                    paper GET    /papers/:id(.:format)                                                                             papers#show
#                                          PATCH  /papers/:id(.:format)                                                                             papers#update
#                                          PUT    /papers/:id(.:format)                                                                             papers#update
#                                          DELETE /papers/:id(.:format)                                                                             papers#destroy
#                        fetch_source_file POST   /papers/:id/fetch_source_file(.:format)                                                           papers#fetch_source_file
#                    generate_auto_summary POST   /papers/:id/generate_auto_summary(.:format)                                                       papers#generate_auto_summary
#                                     root GET    /                                                                                                 papers#index
#         turbo_recede_historical_location GET    /recede_historical_location(.:format)                                                             turbo/native/navigation#recede
#         turbo_resume_historical_location GET    /resume_historical_location(.:format)                                                             turbo/native/navigation#resume
#        turbo_refresh_historical_location GET    /refresh_historical_location(.:format)                                                            turbo/native/navigation#refresh
#            rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#            rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
# new_rails_conductor_inbound_email_source GET    /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
#    rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
#    rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
# rails_conductor_inbound_email_incinerate POST   /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)                            rails/conductor/action_mailbox/incinerates#create
#                       rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#                 rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                          GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#                rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
#          rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                          GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#                       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#                update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#                     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resource :session

  resources :papers

  post "/papers/:id/fetch_source_file", to: "papers#fetch_source_file", as: :fetch_source_file
  post "/papers/:id/generate_auto_summary", to: "papers#generate_auto_summary", as: :generate_auto_summary

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "papers#index"
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  allow_unauthenticated_access only: %i[ index show ]

  before_action :set_paper, only: %i[ show edit update destroy fetch_source_file generate_auto_summary ]

  # GET /papers or /papers.json
  def index
    @papers = Paper.all.with_rich_text_notes_and_embeds
  end

  # GET /papers/1 or /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers or /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: "Paper was successfully created." }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1 or /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: "Paper was successfully updated." }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /papers/1/fetch_source_file
  def fetch_source_file
    respond_to do |format|
      if @paper.fetch_source_file_from_url!
        format.html { redirect_to @paper, notice: "Source file was successfully fetched." }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { redirect_to @paper, alert: @paper.errors.full_messages.join(", ") }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /papers/1/generate_auto_summary
  def generate_auto_summary
    respond_to do |format|
      if @paper.generate_auto_summary!
        format.html { redirect_to @paper }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { redirect_to @paper, alert: @paper.errors.full_messages.join(", ") }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1 or /papers/1.json
  def destroy
    @paper.destroy!

    respond_to do |format|
      format.html { redirect_to papers_path, status: :see_other, notice: "Paper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_paper
    @paper = Paper.find(params.expect(:id))
  end

  def paper_params
    params.expect(paper: [ :url, :title, :read, :authors, :year, :auto_summary, :notes, :source_file ])
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_with(model: paper) do |form| %>
  <% if paper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>
      <ul>
        <% paper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :read, style: "display: block" %>
    <%= form.checkbox :read %>
  </div>
  <div>
    <%= form.label :authors, style: "display: block" %>
    <%= form.text_field :authors %>
  </div>
  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>
  <div>
    <%= form.label :auto_summary, style: "display: block" %>
    <%= form.textarea :auto_summary %>
  </div>
  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.rich_textarea :notes %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/_paper.erb
<%= turbo_frame_tag paper do %>
  <p class="title">
    <%= paper.title.present? ? paper.title : "No title yet." %>
    <%= "(#{paper.year})" if paper.year.present? %>
    <% unless paper.read? %>
      <span class="label-green">NEW</span>
    <% end %>
  </p>
  <p class="author-caption"><%= paper.authors.present? ? paper.authors : "Authors" %></p>
  <% if paper.url.present? %>
    <div class="field-row">
      <p class="form-label">Url</p>
      <p><%= link_to paper.url, paper.url %></p>
    </div>
  <% end %>
  <div class="field-row">
    <p class="form-label">Source file</p>
    <% if paper.source_file.attached? %>
      <p><%= link_to paper.source_file.filename, rails_blob_path(paper.source_file, disposition: "attachment") %></p>
    <% elsif paper.url.present? %>
      <% if authenticated? %>
        <%= button_to "Fetch source file", fetch_source_file_path(paper), class: "button" %>
      <% else %>
        <div class="button disabled">Fetch source file</div>
      <% end %>
    <% else %>
      <p>No source file or url.</p>
    <% end %>
  </div>
  <div class="large-field">
    <p class="form-label">Auto summary</p>
    <% if paper.auto_summary.present? %>
      <p style="white-space:break-spaces;"><%= paper.auto_summary %></p>
    <% else %>
      <% if authenticated? %>
        <%= button_to "Generate", generate_auto_summary_path(paper), class: "button", form_class: "space-top" %>
      <% else %>
        <div class="space-top">
          <div class="button disabled">Generate</div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="large-field">
    <p class="form-label">Notes</p>
    <p><%= paper.notes.present? ? paper.notes : "No notes taken." %></p>
  </div>
<% end %>

app/views/papers/edit.html.erb
<style>
  .form {
    margin-top: 32px;
  }
</style>
<div class="header-row">
  <h1>Paper Matrix</h1>
  <%= link_to "Back to paper", @paper %>
</div>
<p class="instructions">Editing paper.</p>
<% if @paper.url.present? %>
  <div class="field-row">
    <p>Url</p>
    <p><%= link_to @paper.url %></p>
  </div>
<% end %>
<div class="field-row">
  <p>Source file</p>
  <% if @paper.source_file.attached? %>
    <p><%= link_to @paper.source_file.filename, rails_blob_path(@paper.source_file, disposition: "attachment") %></p>
  <% elsif @paper.url.present? %>
    <p><%= button_to "Fetch source file", fetch_source_file_path(@paper), class: "button" %></p>
  <% else %>
    <p>No source file or url.</p>
  <% end %>
</div>
<%= form_with(model: @paper, class: "form") do |form| %>
  <div class="field-row">
    <%= form.label :title, class: "form-label" %>
    <div class="grow">
      <%= form.text_field :title %>
      <p class="form-field-errors"><%= @paper.errors.messages[:title].join(", ") if @paper.errors.messages[:title].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="field-row">
    <%= form.label :authors, class: "form-label" %>
    <div class="grow">
      <%= form.text_field :authors %>
      <p class="form-field-errors"><%= @paper.errors.messages[:authors].join(", ") if @paper.errors.messages[:authors].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="field-row">
    <%= form.label :year, class: "form-label" %>
    <div class="grow">
      <%= form.number_field :year, placeholder: 2024, step: 1, style: "width: auto;" %>
      <p class="form-field-errors"><%= @paper.errors.messages[:year].join(", ") if @paper.errors.messages[:year].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="field-row">
    <%= form.label :auto_summary, class: "form-label" %>
    <div class="grow">
      <%= form.text_area :auto_summary %>
      <p class="form-field-errors"><%= @paper.errors.messages[:auto_summary].join(", ") if @paper.errors.messages[:auto_summary].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="field-row">
    <%= form.label :notes, class: "form-label" %>
    <div class="grow">
      <%= form.rich_textarea :notes %>
      <p class="form-field-errors"><%= @paper.errors.messages[:notes].join(", ") if @paper.errors.messages[:notes].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="field-row">
    <%= form.label :read, class: "form-label" %>
    <div class="grow">
      <%= form.checkbox :read %>
      <p class="form-field-errors"><%= @paper.errors.messages[:read].join(", ") if @paper.errors.messages[:read].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="submit">
    <%= form.submit class: "button" %>
    <p class="form-field-errors"><%= @paper.errors.messages[:base].join(", ") if @paper.errors.messages[:base].any? %>&nbsp;</p>
  </div>
<% end %>

app/views/papers/index.html.erb
<style>
  .header-button {
    display: inline-block;
    height: 36.4px;
  }

  @media screen and (max-width: 768px) {
    .header-button {
      transform: none;
      margin-top: 8px;
      margin-bottom: 24px;
    }
  }

  .papers-list-item {
    display: block;
    margin-bottom: 24px;
    text-decoration: none;

    &:hover {
        text-decoration: none;
    }
  }
</style>
<div class="header-row">
  <h1>Paper Matrix</h1>
  <% if authenticated? %>
    <div>
      <%= link_to "Add Paper", new_paper_path, class: "button header-button" %>
      <%= button_to "Logout", {controller: :sessions, action: "destroy"}, method: :delete, class: "button header-button", form_class: "button-container" %>
    </div>
  <% else %>
    <div>
      <div class="button header-button disabled">Add Paper</div>
      <%= link_to "Sign in", new_session_path, class: "button header-button" %>
    </div>
  <% end %>
</div>
<div id="papers">
  <% @papers.each do |paper| %>
    <%= link_to paper, class: "papers-list-item" do %>
      <p>
        <%= paper.title.present? ? paper.title : "No Title Yet" %>
        <%= "(#{paper.year})" if paper.year.present? %>
        <% unless paper.read? %>
          <span class="label-green">NEW</span>
        <% end %>
      </p>
      <p class="author-caption"><%= paper.authors.present? ? paper.authors : "Authors" %></p>
    <% end %>
  <% end %>
</div>

app/views/papers/new.html.erb
<style>
  .or {
    font-weight: 600;
    font-style: italic;
    width: 100%;
    text-align: center;
    margin-bottom: 24px;
  }


  @media screen and (max-width: 768px) {
    .or {
        text-align: left;
    }
  }
</style>
<div class="header-row">
  <h1>Paper Matrix</h1>
  <%= link_to "Back to list", root_path %>
</div>
<p class="instructions">Add a paper. Either upload a pdf or enter a url.</p>
<%= form_with(model: @paper) do |form| %>
  <div class="field-row">
    <%= form.label :url, class: "form-label" %>
    <div class="grow">
      <%= form.text_field :url %>
      <p class="form-field-errors"><%= @paper.errors.messages[:url].join(", ") if @paper.errors.messages[:url].any? %>&nbsp;</p>
    </div>
  </div>
  <p class="or">OR</p>
  <div class="field-row">
    <%= form.label :source_file, class: "form-label" %>
    <div class="grow">
      <%= form.label :source_file, "Browse...", class: "button form-button" %>
      <%= form.file_field :source_file %>
      <p class="form-field-errors"><%= @paper.errors.messages[:source_file].join(", ") if @paper.errors.messages[:source_file].any? %>&nbsp;</p>
    </div>
  </div>
  <div class="submit">
    <%= form.submit class: "button" %>
    <p class="form-field-errors"><%= @paper.errors.messages[:base].join(", ") if @paper.errors.messages[:base].any? %>&nbsp;</p>
  </div>
<% end %>

app/views/papers/show.html.erb
<style>
  .title {
    font-size: 1.1rem;
  }

  .author-caption {
    margin-bottom: 32px;
  }

  .large-field {
    margin-top: 32px;
    margin-bottom: 32px;
  }

  .space-top {
    margin-top: 12px;
  }

  .buttons {
    display: flex;
    flex-direction: row;
    justify-content: flex-start;
    gap: 18px;
  }
</style>
<div class="header-row">
  <h1>Paper Matrix</h1>
  <%= link_to "Back to list", root_path %>
</div>
<%= turbo_stream_from @paper %>
<%= render @paper %>
<div class="buttons">
  <% if authenticated? %>
    <div><%= link_to "Edit Paper", edit_paper_path(@paper), class: "button" %></div>
    <div><%= button_to "Delete Paper", @paper, method: :delete, class: "button button-warning", form_class: "button-container" %></div>
  <% else %>
    <div class="button disabled">Edit Paper</div>
    <div class="button disabled">Delete Paper</div>
  <% end %>
</div>